/**
 * Chronological combat log — a drawer over the tracker, newest first.
 * Every entry is generated by the reducer, so the log can never drift from
 * what actually happened to the encounter.
 */

import { useMemo, useState } from "react";
import { PHASES } from "@/domain/constants";
import { useStore } from "@/state/store";
import type { LogEntry } from "@/state/reducer";
import { useEscapeKey } from "./hooks";
import { EmptyState } from "./primitives";
import "./eventlog.css";

const KIND_LABEL: Record<LogEntry["kind"], string> = {
  damage: "Damage",
  heal: "Healing",
  status: "Condition",
  flow: "Flow",
  roster: "Roster",
  ability: "Ability",
  shield: "Shield",
};

const FILTERS: (LogEntry["kind"] | "all")[] = [
  "all",
  "damage",
  "heal",
  "status",
  "ability",
  "flow",
];

export function EventLog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { log } = useStore();
  const [filter, setFilter] = useState<LogEntry["kind"] | "all">("all");
  // Deliberately not a focus trap. This is a non-modal side drawer that stays
  // open while the GM works in the tracker, so trapping Tab inside it would
  // strand keyboard users. Escape still closes it.
  useEscapeKey(open, onClose);

  const entries = useMemo(
    () => (filter === "all" ? log : log.filter((e) => e.kind === filter)),
    [log, filter],
  );

  if (!open) return null;

  return (
    <aside className="eventlog" aria-label="Combat log">
      <header className="eventlog__head">
        <h2 className="eventlog__title display">Combat log</h2>
        <button type="button" className="eventlog__close" onClick={onClose} aria-label="Close combat log">
          ✕
        </button>
      </header>

      <div className="eventlog__filters" role="group" aria-label="Filter log">
        {FILTERS.map((f) => (
          <button
            key={f}
            type="button"
            className="eventlog__filter"
            data-active={filter === f ? "1" : undefined}
            aria-pressed={filter === f}
            onClick={() => setFilter(f)}
          >
            {f === "all" ? "All" : KIND_LABEL[f]}
          </button>
        ))}
      </div>

      {entries.length === 0 ? (
        <EmptyState
          seal="記"
          title="Nothing recorded yet"
          body="Damage, healing, conditions, and phase changes will appear here as the fight unfolds."
        />
      ) : (
        <ol className="eventlog__list">
          {entries.map((e) => (
            <li key={e.id} className="eventlog__entry" data-kind={e.kind}>
              <span className="eventlog__when tnum">
                R{e.round}·{PHASES[e.phase]?.[0]}
              </span>
              <span className="eventlog__text">{e.text}</span>
            </li>
          ))}
        </ol>
      )}
    </aside>
  );
}
